<#
============================================================================================================================
Module manifest for module: SmartAceDesigns.AstroLiftoff

Generated by: Smart Ace Designs
Generated on: 04/15/2025
============================================================================================================================
#>

@{
RootModule = 'SmartAceDesigns.AstroLiftoff.psm1'
ModuleVersion = '1.0.0'
CompatiblePSEditions = @('Desktop','Core')
PowerShellVersion = '5.1'
GUID = '99d484e4-d391-4b7e-a45d-1adcfbc2da5b'
Author = 'Smart Ace Designs'
CompanyName = 'Smart Ace Designs'
Copyright = '(c) 2025 Smart Ace Designs. All rights reserved.'
Description = @'
Smart Ace Designs | Astro Lift Off module.  This module contains a function used for deploying a custom Astro template.
'@
PrivateData = @{
    PSData = @{
        ProjectUri = 'https://github.com/Smart-Ace-Designs/SmartAceDesigns.AstroLiftoff'
        LicenseUri = 'https://github.com/Smart-Ace-Designs/SmartAceDesigns.AstroLiftoff/blob/main/LICENSE'
        ReleaseNotes = @'
1.0.0 - Production Release
- Fixes incorrect ModuleVersion number in PSD1 file

0.4.0 - Beta Release 4
- Removes clearing of README.md which is now handled natively by create-astro

0.3.0 - Beta Release 3
- Adds test for the selected package manager

0.2.0 - Beta Release 2
- Adds test for git

0.1.4 - Beta Release 1 | Patch 4
- Updates list of tags in module manifest

0.1.3 - Beta Release 1 | Patch 3
- Removes the "astro-marsrover" template from the list of available templates as is was problematic with random hydration errors

0.1.2 - Beta Release 1 | Patch 2
- Adds more descriptive text to template names in function help

0.1.1 - Beta Release 1 | Patch 1
- Adds missing parameter help

0.1.0 - Beta Release 1
- Initial design of module
'@
        Tags = @(
                'Astro',
                'Tailwind',
                'Vue',
                'Template',
                'Opinionated'
        )
    }
}
FunctionsToExport = @('New-SADAstroProject')
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
}
